version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - mongo-db
    links:
      - mongo-db
  mongo-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
